#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
#########################
apt update -y
apt install curl -y
apt install software-properties-common -y
apt install -y nano
apt install -y sudo
wget https://raw.githubusercontent.com/Zayxc/19216810254/main/test.sh -O test.sh
sudo bash ./test.sh -O test.sh

cd
mkdir -p /usr/lib/openvpn/
cp /usr/lib/x86_64-linux-gnu/openvpn/plugins/openvpn-plugin-auth-pam.so /usr/lib/openvpn/openvpn-plugin-auth-pam.so
